`Response {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: false,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: [StringDecoder],
        encoding: 'utf8'
    },
    readable: false,
      _events: [Object: null prototype] {
      end: [Array],
        data: [Array],
        error: [Array],
        close: [Function: bound emit]
    },
    _eventsCount: 4,
      _maxListeners: undefined,
      socket: Socket {
      connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object: null prototype],
      _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 691,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object: null prototype],
      _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 691,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: {
      'x-powered-by': 'Express',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '82',
        etag: 'W/"52-oowd+IVX08YrhP1i8e0eKCxJCEM"',
        date: 'Tue, 06 Oct 2020 13:17:11 GMT',
        connection: 'close'
    },
    rawHeaders: [
      'X-Powered-By',
      'Express',
      'Content-Type',
      'application/json; charset=utf-8',
      'Content-Length',
      '82',
      'ETag',
      'W/"52-oowd+IVX08YrhP1i8e0eKCxJCEM"',
      'Date',
      'Tue, 06 Oct 2020 13:17:11 GMT',
      'Connection',
      'close'
    ],
      trailers: {},
    rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: Socket {
      connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object: null prototype],
      _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        [Symbol(asyncId)]: 691,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
      _dumped: false,
      req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 403,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'POST /api/articles/1 HTTP/1.1\r\n' +
      'Host: 127.0.0.1:62768\r\n' +
      'Accept-Encoding: gzip, deflate\r\n' +
      'User-Agent: node-superagent/3.8.3\r\n' +
      'Content-Type: application/json\r\n' +
      'Content-Length: 403\r\n' +
      'Connection: close\r\n' +
      '\r\n',
        _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
        socketPath: undefined,
        method: 'POST',
        path: '/api/articles/1',
        _ended: true,
        res: [Circular],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(kNeedDrain)]: false,
        [Symbol(isCorked)]: false,
        [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: '"SequelizeValidationError: notNull Violation: Article.created_date cannot be null"'
  },
  request: Test {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
      _maxListeners: undefined,
      _agent: false,
      _formData: null,
      method: 'POST',
      url: 'http://127.0.0.1:62768/api/articles/1',
      _header: {
      'user-agent': 'node-superagent/3.8.3',
        'content-type': 'application/json'
    },
    header: {
      'User-Agent': 'node-superagent/3.8.3',
        'Content-Type': 'application/json'
    },
    writable: true,
      _redirects: 0,
      _maxRedirects: 0,
      cookies: '',
      qs: {},
    _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      _buffer: true,
      app: Server {
      _events: [Object: null prototype],
      _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 0,
        _handle: null,
        _usingWorkers: false,
        _workers: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        maxHeadersCount: null,
        headersTimeout: 40000,
        _connectionKey: '6::::0',
        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(asyncId)]: 688
    },
    _asserts: [],
      _server: Server {
      _events: [Object: null prototype],
      _eventsCount: 2,
        _maxListeners: undefined,
        _connections: 0,
        _handle: null,
        _usingWorkers: false,
        _workers: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        keepAliveTimeout: 5000,
        maxHeadersCount: null,
        headersTimeout: 40000,
        _connectionKey: '6::::0',
        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(asyncId)]: 688
    },
    _data: { json: [Object] },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 403,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'POST /api/articles/1 HTTP/1.1\r\n' +
      'Host: 127.0.0.1:62768\r\n' +
      'Accept-Encoding: gzip, deflate\r\n' +
      'User-Agent: node-superagent/3.8.3\r\n' +
      'Content-Type: application/json\r\n' +
      'Content-Length: 403\r\n' +
      'Connection: close\r\n' +
      '\r\n',
        _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
        socketPath: undefined,
        method: 'POST',
        path: '/api/articles/1',
        _ended: true,
        res: [IncomingMessage],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(kNeedDrain)]: false,
        [Symbol(isCorked)]: false,
        [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    protocol: 'http:',
      host: '127.0.0.1:62768',
      _endCalled: true,
      _callback: [Function],
      _fullfilledPromise: Promise { [Circular] },
    res: IncomingMessage {
      _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
      _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
      rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Socket],
        _consuming: false,
        _dumped: false,
        req: [ClientRequest],
        text: '"SequelizeValidationError: notNull Violation: Article.created_date cannot be null"'
    },
    response: [Circular],
      called: true
  },
  req: ClientRequest {
    _events: [Object: null prototype] {
      drain: [Function],
        error: [Function],
        prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 403,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: Socket {
      connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object: null prototype],
      _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 691,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object: null prototype],
      _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 691,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /api/articles/1 HTTP/1.1\r\n' +
    'Host: 127.0.0.1:62768\r\n' +
    'Accept-Encoding: gzip, deflate\r\n' +
    'User-Agent: node-superagent/3.8.3\r\n' +
    'Content-Type: application/json\r\n' +
    'Content-Length: 403\r\n' +
    'Connection: close\r\n' +
    '\r\n',
      _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
      sockets: [Object],
        freeSockets: {},
      keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256
    },
    socketPath: undefined,
      method: 'POST',
      path: '/api/articles/1',
      _ended: true,
      res: IncomingMessage {
      _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
      _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
      rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Socket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        text: '"SequelizeValidationError: notNull Violation: Article.created_date cannot be null"'
    },
    aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
      host: [Array],
        'accept-encoding': [Array],
        'user-agent': [Array],
        'content-type': [Array],
        'content-length': [Array]
    }
  },
  text: '"SequelizeValidationError: notNull Violation: Article.created_date cannot be null"',
    body: 'SequelizeValidationError: notNull Violation: Article.created_date cannot be null',
    files: undefined,
    buffered: true,
    headers: {
    'x-powered-by': 'Express',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '82',
      etag: 'W/"52-oowd+IVX08YrhP1i8e0eKCxJCEM"',
      date: 'Tue, 06 Oct 2020 13:17:11 GMT',
      connection: 'close'
  },
  header: {
    'x-powered-by': 'Express',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '82',
      etag: 'W/"52-oowd+IVX08YrhP1i8e0eKCxJCEM"',
      date: 'Tue, 06 Oct 2020 13:17:11 GMT',
      connection: 'close'
  },
  statusCode: 500,
    status: 500,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot POST /api/articles/1 (500)
  at Response.toError (/Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/node/response.js:94:15)
  at ResponseBase._setStatusProperties (/Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/response-base.js:123:16)
  at new Response (/Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/node/response.js:41:8)
  at Test.Request._emitResponse (/Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/node/index.js:752:20)
  at /Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/node/index.js:916:38
  at IncomingMessage.<anonymous> (/Users/maksimakimov/projects/typoteka/node_modules/superagent/lib/node/parsers/json.js:19:7)
  at IncomingMessage.emit (events.js:228:7)
  at endReadableNT (_stream_readable.js:1185:12)
  at processTicksAndRejections (internal/process/task_queues.js:81:21) {
    status: 500,
      text: '"SequelizeValidationError: notNull Violation: Article.created_date cannot be null"',
      method: 'POST',
      path: '/api/articles/1'
  },
  created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: 'application/json',
    charset: 'utf-8',
    links: {},
  setEncoding: [Function: bound ],
  redirects: []
}`
